### ISSUE TITLE
Active admin paper edit 500 error

### ISSUE THREAD

**Issue by SalmaTalbi** [sbounmy/hongbao_bitcoin#140]
![Image](https://github.com/user-attachments/assets/770e11ad-0c3e-4a11-805e-019e4985fb92)

**Comment by sbounmy** [comment]
fixed. forgot to run db:migrate 😅

**Comment by SalmaTalbi** [comment]
@sbounmy the issue still exists in live
is it not deployed yet?

**Comment by sbounmy** [comment]
@SalmaTalbi I dont have the issue 
hongbaob.tc/admin
<img width="1493" alt="Image" src="https://github.com/user-attachments/assets/88d8f618-73bb-4340-93f5-c93ddf1cff09" />

**Comment by SalmaTalbi** [comment]
the issue appears only for paper edit
